version: "3.5"

services:
    chillbot:
        build:
            context: .
        image: "morria/chillbot:latest"
        container_name: "chillbot"
        restart: "unless-stopped"
        user: "1000"
        ports:
            - "8085:3000"
        env_file: ./environment
        environment:
            VIRTUAL_HOST: "chillbot.lepton.work"
            VIRTUAL_PORT: 8085
            LETSENCRYPT_HOST: "chillbot.lepton.work"
        networks: ["server"]

networks:
   server:
       external: true

